### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by ChillarAnand** [rakeshvar/chamanti_ocr#10]
While training, scribe is generating random characters. Since we are using a CTC layer, should we use valid words to maintain order while training?

**Comment by rakeshvar** [comment]
There are a couple of reasons here. (1) The number of 'words' in Telugu and other agglutinative languages is limitless. Even the conventions for placing a space are not fixed in Telugu. We do not want the NN to recognize words as a whole, we want it to be able to tell individual letters (aksharams). (2) The characters are not completely random, they come from an n-gram, so if you consider pairs of adjacent characters, they are highly likely in real text.

**Comment by ChillarAnand** [comment]
> We do not want the NN to recognize words as a whole, we want it to be able to tell individual letters (aksharams).

I misunderstood CTC layer initially. Thanks for providing a working example at  https://github.com/rakeshvar/rnn_ctc
